name: Continues integration - Movie recommendation app

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  concurrency:
    group: movie_app_ci
    cancel-in-progress: true

  permissions:
    contents: read
    id-token: write

jobs:
  build-fargate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
